[workspace]
resolver = "3"
default-members = ["files"]
members = ["files"]

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
image = "0.25.10"

[workspace.dependencies.tokio]
version = "1.52.3"
features = ["rt", "macros", "rt-multi-thread", "sync"]

[workspace.dependencies.iced]
version = "0.13.1"
features = ["image", "tokio"]
